
# Defines class Album
class Album:
    # Constructor contains Album attributes
    def __init__(self, album_name, number_of_songs, album_artist):
        self.album_name = album_name
        self.number_of_songs = number_of_songs
        self.album_artist = album_artist
    # Str method enables printing of list objects as strings
    # Source used as reference for function can be found at: 
    # https://youtu.be/6ualOSJGY9w

    def __str__(self):
        
        return f"{self.album_name}, {self.number_of_songs}, {self.album_artist}"

    # Function required to print list objects
    # Source for referencing function can be found at: 
    # https://www.geeksforgeeks.org/python/sorting-objects-of-user-defined-class-in-python/
    def __repr__(self):
        return str((self.album_name, self.number_of_songs, self.album_artist))

# album_one = Album("Havok", "12", "Mary J Blige")
# print(album_one)

# Creates a list of 5 Album objects and stores in "albums1"
# Microsoft copilot used to generate randon albums, numbers and artists
albums1 = [Album("The Last Summer Signal", 11,"Ocean Avenue"),
           Album("Fragments of Tomorrow", 10,"The Static Line"),
           Album("Neon Horizons", 14,"Aurora Drive"),
           Album("Beyond the Silver Sky", 9,"Atlas Rising"), 
           Album("Midnight Echoes", 12, "Luna Hart"),
           ]

print("The albums in Album 1 are: \n",)
# For loop prints each element in list
for album in albums1: 
    print(album)

# List pbjects sorted by album size
# Source used to reference key parameter can be found at: 
# https://www.geeksforgeeks.org/python/sorting-objects-of-user-defined-class-in-python/

sort_by_size = sorted(albums1, key = lambda album: album.number_of_songs)

print("\nThe size sorted albums are: \n")
for album in sort_by_size:
    print(album)

# Defines function to swap first and second list objects
# Logic for swapping function usesthe following reference: 
# https://www.youtube.com/watch?v=uXEW1eUsMDk
def swap_albums(album_list):
    album_list[0], album_list[1] = album_list[1], album_list[0]
    return album_list

swap_albums(albums1)

# Define new list "albums2"
albums2 = [
        # Stores 5 more album objects in list
        # Album object attributes randomly generated by Microsoft Copilot
        Album("Shadows in Motion", 13, "Velvet Storm"),
        Album("Electric Daydreams", 8, "Nova Pulse"),
        Album("Waves of Silence", 15, "Crystal Harbour"),
        Album("Golden Afterglow", 10, "Sunset Theory"),
        Album("Parallel Skies", 7, "Echo District")
            ]

print("\nThe albums in Album 2 are: \n")
# Prints out class objects within "album2"
for album in albums2:
    print(album)

# Adds two list objects "albums1" and "albuyms2" together
albums1_and_2 = albums1 + albums2
# Prints concatenated list to console
print("\nThe albums in Album 1 and 2 are: \n")
for album in albums1_and_2:
    print(album)

# List of extra albums to add to list
extra_albums = [Album("Dark Side of the Moon",9, "Pink Floyd"),
                 Album("Oops! . I Did It Again", 16, "Britney Spears",)]
# List operation extend used to add extra albums to "alnums2"
albums2.extend(extra_albums)

print("\nThe list with extra albums is: \n")
for album in albums2: 
    print(album)

# Albums are sorted alphabetically
# The source for sorting with a key for strings can be found at: 
# https://docs.python.org/3/howto/sorting.html
sort_by_name = sorted(albums2, key = lambda album: album.album_name.casefold())
for album in sort_by_name:
    print(album)


# Use binary search to find target album as it's sorted in previous step already
# Reference for structure of function used is the "Sorting and Searching.pdf"
# Define binary 
def binary_search(target, items): 
    # Assign lis indice range to low and high variables
    low, high = 0, len(items) - 1 
 
    # iterate through list until low and high meet 
    while high >= low: 
        # Define midpoint as the middle value of the meeting point
        mid = (low + high) // 2 
 
        # Checks if item is at midpoint and returns
        if items[mid].album_name == target: 
            return mid 
        # Searches up the list if not the target 
        elif items[mid].album_name < target: 
            low = mid + 1 
        # Searches down the list if not the target
        else: 
            high = mid - 1 
 
    # Condition if target not in list
    return None 
 
 
# Calls function 
result = binary_search("Dark Side of the Moon", sort_by_name)

print("The target item is at index: ", result)
